
Turn 2
================================================================
error: failed to decode bot message: "T" (at position 1)
Last input received was:
Traceback (most recent call last):
  File "MyBot2.py", line 134, in <module>
    prev_location[ship.id] = current_location[ship.id]
KeyError: 1

